name: Publish

on:
  push:
    branches:
      - 'master'
      - 'canary'

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Publish
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
          GIT_AUTHOR_NAME: "Shaun O'Neill"
          GIT_AUTHOR_EMAIL: ${{ secrets.RELEASE_BOT_EMAIL }}
          GIT_COMMITTER_NAME: "Shaun O'Neill"
          GIT_COMMITTER_EMAIL: ${{ secrets.RELEASE_BOT_EMAIL }}

  update-canary:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [release]
    name: Update canary
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'canary'
          token: ${{ secrets.GH_TOKEN }}

      - name: Back-merge main into canary
        run: |
          git merge --ff-only origin/main
          git push
