name: Quality

on:
  pull_request:
  push:
    branches:
      - 'master'
      - 'canary'

jobs:
  commitlint:
    name: 'Commitlint'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run commitlint check
        run: yarn commitlint -f ${{ github.event.pull_request.base.sha }}

  eslint:
    name: 'ESLint'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run ESLint check
        run: yarn lint

  prettier:
    name: 'Prettier'
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Prettier check
        run: yarn prettier-check
