name: Release

on:
  workflow_dispatch:
    inputs:
      acknowledge:
        description: 'I understand that this action will publish everything on canary to the latest tag'
        required: true
        type: boolean

jobs:
  release:
    if: ${{ inputs.acknowledge }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'main'
          token: ${{ secrets.GH_TOKEN }}

      - name: Merge canary into main
        run: |
          git merge --ff-only origin/canary
          git push
